version: '3.3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      # - POSTGRES_DB=154499
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d
    ports:
      - 5436:5432

  nodejs:
    image: node
    container_name: nodejs
    working_dir: /nodejs
    restart: always
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs:/nodejs
    ports:
      - 3300:3000
    command: bash -c "npm i && npm i -g nodemon && npm i -g pm2 && nodemon server.js"
